import { Iproduct } from "./product.interface";




export const mobileProducts: Iproduct[] = [
    {
        prodId: "1",
        brand: "Samsung",
        image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg",
        model: "Galaxy S21",
        color: "Phantom Black",
        rating: 4,
        storage: "128GB",
        price: "74,000",
        screen_size: "6.2",
        processor: "Exynos 2100",
        battery_capacity: 4000,
        canReturn: "1"
    },
    {
        prodId: "2",
        brand: "Apple",
        image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
        model: "iPhone 13 Pro",
        color: "Graphite",
        storage: "256GB",
        rating: 4,
        price: "1,03,900",
        screen_size: "6.1",
        processor: "A15 Bionic",
        battery_capacity: 3095,
        canReturn: "1"
    },
    {
        prodId: "3",
        brand: "OnePlus",
        image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro-.jpg",
        model: "9 Pro",
        color: "Morning Mist",
        storage: "256GB",
        price: "80,000",
        rating: 3,
        screen_size: "6.7",
        processor: "Snapdragon 888",
        battery_capacity: 4500,
        canReturn: "1"
    },
    {
        prodId: "4",
        brand: "Google",
        image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
        model: "Pixel 6",
        color: "Sorta Sunny",
        storage: "128GB",
        price: "58,500",
        rating: 3,
        screen_size: "6.4",
        processor: "Google Tensor",
        battery_capacity: 4614,
        canReturn: "0"
    },
    {
        prodId: "5",
        brand: "Xiaomi",
        image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi11-ultra-5g-k1.jpg",
        model: "Mi 11",
        color: "Midnight Gray",
        storage: "256GB",
        price: "55,000",
        rating: 3,
        screen_size: "6.81",
        processor: "Snapdragon 888",
        battery_capacity: 4600,
        canReturn: "1"
    },
    {
        prodId: "6",
        brand: "Huawei",
        image: "https://fdn2.gsmarena.com/vv/bigpic/huawei-p40-pro.jpg",
        model: "P40 Pro",
        color: "Silver Frost",
        storage: "256GB",
        price: "64,900",
        rating: 3,
        screen_size: "6.58",
        processor: "Kirin 990 5G",
        battery_capacity: 4200,
        canReturn: "0"
    },
    {
        prodId: "7",
        brand: "Sony",
        image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-iii.jpg",
        model: "Xperia 1 III",
        color: "Frosted Black",
        storage: "256GB",
        price: "92,900",
        rating: 3,
        screen_size: "6.5",
        processor: "Snapdragon 888",
        battery_capacity: 4500,
        canReturn: "0"
    },
    {
        prodId: "8",
        brand: "Motorola",
        image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-plus-2023.jpg",
        model: "Edge+",
        color: "Thunder Grey",
        storage: "256GB",
        rating: 2,
        price: "74,000",
        screen_size: "6.7",
        processor: "Snapdragon 865",
        battery_capacity: 5000,
        canReturn: "1"
    },
    {
        prodId: "9",
        brand: "LG",
        image: "https://fdn2.gsmarena.com/vv/bigpic/lg-wing.jpg",
        model: "Wing 5G",
        color: "Aurora Gray",
        storage: "256GB",
        price: "74,000",
        rating: 2,
        screen_size: "6.8",
        processor: "Snapdragon 765G",
        battery_capacity: 4000,
        canReturn: "0"
    },
    {
        prodId: "10",
        brand: "Realme",
        image: "https://fdn2.gsmarena.com/vv/bigpic/realme-gt-neo2.jpg",
        model: "GT Neo 2",
        color: "Neo Green",
        storage: "128GB",
        price: "28,000",
        rating: 2,
        screen_size: "6.62",
        processor: "Snapdragon 870",
        battery_capacity: 5000,
        canReturn: "1"
    }
];
